FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"bmFtZTogYnVpbGRmYXJtLWFwYgppbWFnZTogZmVlZGhlbnJ5L2Flcm9nZWFyLWRpZ2dlci1hcGIK\
ZGVzY3JpcHRpb246IE1vYmlsZSBDSS9DRCBzZXJ2aWNlIHRoYXQgaW50ZWdyYXRlcyB3aXRoIEpl\
bmtpbnMgUGlwZWxpbmVzIHRvIHRlc3QgYW5kIGJ1aWxkIHlvdXIgbW9iaWxlIGJpbmFyaWVzLgpi\
aW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFsCnRhZ3M6CiAgLSBtb2JpbGUtc2VydmljZQpt\
ZXRhZGF0YToKICBkaXNwbGF5TmFtZTogTW9iaWxlIENJL0NECiAgbG9uZ0Rlc2NyaXB0aW9uOiAi\
VG8gdXNlIHRoZSBNb2JpbGUgQ0kvQ0Qgc2VydmljZSB5b3UgbXVzdCBmaXJzdCBhZ3JlZSB0byB0\
aGUgQW5kcm9pZCBTREsgTGljZW5zZSBBZ3JlZW1lbnQuIEJ5IGNoZWNraW5nIHRoaXMgYm94IHlv\
dSBhcmUgYWdyZWVpbmcgdG8gdGhlIEFuZHJvaWQgU29mdHdhcmUgRGV2ZWxvcG1lbnQgS2l0IExp\
Y2Vuc2UgYWdyZWVtZW50IHdoaWNoIGNhbiBiZSByZWFkIGF0IHRoZSBmb2xsb3dpbmcgVVJMOiBo\
dHRwczovL2RldmVsb3Blci5hbmRyb2lkLmNvbS9zdHVkaW8vdGVybXMuaHRtbFxuXG4uIElmIHRo\
ZSBib3ggaXMgbm90IGNoZWNrZWQgdGhlIGluc3RhbGxlciB3aWxsIHRha2Ugbm8gYWN0aW9uLiIK\
ICBjb25zb2xlLm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZvbnQtaWNvbiBpY29uLWplbmtpbnMK\
cGxhbnM6CiAgLSBuYW1lOiBkZWZhdWx0CiAgICBkZXNjcmlwdGlvbjogRGVmYXVsdCBwbGFuCiAg\
ICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6CiAgICAtIG5hbWU6\
IEFORFJPSURfTElDRU5TRV9BR1JFRU1FTlQKICAgICAgZGVmYXVsdDogIiIKICAgICAgcGF0dGVy\
bjogXnllcyQKICAgICAgdHlwZTogc3RyaW5nCiAgICAgIGRlc2NyaXB0aW9uOiAiVHlwZSAneWVz\
JyBhYm92ZSB0byBhY2NlcHQgdGhlIEFuZHJvaWQgU0RLIExpY2Vuc2UgQWdyZWVtZW50LiBodHRw\
czovL2RldmVsb3Blci5hbmRyb2lkLmNvbS9zdHVkaW8vdGVybXMuaHRtbCIKICAgICAgdGl0bGU6\
IEFuZHJvaWQgU0RLIExpY2Vuc2UgQWdyZWVtZW50CiAgICAgIHJlcXVpcmVkOiBUcnVlCg=="































COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
