FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGFlcm9nZWFyLWRpZ2dlci1hcGIKZGVzY3JpcHRpb246IE1vYmls\
ZSBDSS9DRCBzZXJ2aWNlIHRoYXQgaW50ZWdyYXRlcyB3aXRoIEplbmtpbnMgUGlwZWxpbmVzIHRv\
IHRlc3QgYW5kIGJ1aWxkIHlvdXIgbW9iaWxlIGJpbmFyaWVzLgpiaW5kYWJsZTogRmFsc2UKYXN5\
bmM6IG9wdGlvbmFsCnRhZ3M6CiAgLSBtb2JpbGUtc2VydmljZQptZXRhZGF0YToKICBkaXNwbGF5\
TmFtZTogTW9iaWxlIENJL0NECiAgbG9uZ0Rlc2NyaXB0aW9uOiAiVG8gdXNlIHRoZSBNb2JpbGUg\
Q0kvQ0Qgc2VydmljZSB5b3UgbXVzdCBmaXJzdCBhZ3JlZSB0byB0aGUgQW5kcm9pZCBTREsgTGlj\
ZW5zZSBBZ3JlZW1lbnQuIEJ5IGNoZWNraW5nIHRoaXMgYm94IHlvdSBhcmUgYWdyZWVpbmcgdG8g\
dGhlIEFuZHJvaWQgU29mdHdhcmUgRGV2ZWxvcG1lbnQgS2l0IExpY2Vuc2UgYWdyZWVtZW50IHdo\
aWNoIGNhbiBiZSByZWFkIGF0IHRoZSBmb2xsb3dpbmcgVVJMOiBodHRwczovL2RldmVsb3Blci5h\
bmRyb2lkLmNvbS9zdHVkaW8vdGVybXMuaHRtbFxuXG4uIElmIHRoZSBib3ggaXMgbm90IGNoZWNr\
ZWQgdGhlIGluc3RhbGxlciB3aWxsIHRha2Ugbm8gYWN0aW9uLiIKICBjb25zb2xlLm9wZW5zaGlm\
dC5pby9pY29uQ2xhc3M6IGZvbnQtaWNvbiBpY29uLWplbmtpbnMKcGxhbnM6CiAgLSBuYW1lOiBk\
ZWZhdWx0CiAgICBkZXNjcmlwdGlvbjogRGVmYXVsdCBwbGFuCiAgICBmcmVlOiBUcnVlCiAgICBt\
ZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6CiAgICAtIG5hbWU6IEFORFJPSURfTElDRU5TRV9B\
R1JFRU1FTlQKICAgICAgZGVmYXVsdDogIiIKICAgICAgcGF0dGVybjogXnllcyQKICAgICAgdHlw\
ZTogc3RyaW5nCiAgICAgIGRlc2NyaXB0aW9uOiAiVHlwZSAneWVzJyBhYm92ZSB0byBhY2NlcHQg\
dGhlIEFuZHJvaWQgU0RLIExpY2Vuc2UgQWdyZWVtZW50LiBodHRwczovL2RldmVsb3Blci5hbmRy\
b2lkLmNvbS9zdHVkaW8vdGVybXMuaHRtbCIKICAgICAgdGl0bGU6IEFuZHJvaWQgU0RLIExpY2Vu\
c2UgQWdyZWVtZW50CiAgICAgIHJlcXVpcmVkOiBUcnVlCg=="































COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
